name: banking
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  # For store data
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Router
  go_router: ^10.0.0
  # State managment
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  # Google fonts
  google_fonts: ^5.1.0
  # Freezed
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  # Service locator
  get_it: ^7.6.0
  # Form validate
  formz: ^0.6.0
  # Clock
  clock: ^1.1.1

dev_dependencies:
  # Code gen
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  go_router_builder: ^2.2.4

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
